version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: skillhub_redis
    restart: unless-stopped  
    ports:
      - "6379:6379"

  app1:
    build: .
    container_name: skillhub_app1
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    expose:
      - "5000"

  app2:
    build: .
    container_name: skillhub_app2
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    container_name: skillhub_nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    driver: bridge
